use skilldock_core::model::*;
use ts_rs::TS;
fn main() {
    let declarations = [
        Policy::decl(),
        Skill::decl(),
        Source::decl(),
        Target::decl(),
        Binding::decl(),
        Preset::decl(),
        Task::decl(),
        CatalogSite::decl(),
        AgentProfile::decl(),
        NetworkProxy::decl(),
        Settings::decl(),
        PackageScope::decl(),
        SkillPackage::decl(),
        PresetPackage::decl(),
        PresetApplication::decl(),
        ExternalInstallation::decl(),
        Snapshot::decl(),
        ScanItem::decl(),
        ScanResult::decl(),
        CatalogItem::decl(),
        CatalogResult::decl(),
        PlanReplacement::decl(),
        PlanItem::decl(),
        DistributionPlan::decl(),
    ];
    let output = format!(
        "// Generated by cargo run -p skilldock-core --example export_types. Do not edit.\n{}\nexport type Request = {{ action: string; [key: string]: unknown }}\n",
        declarations
            .iter()
            .map(|decl| format!("export {decl}"))
            .collect::<Vec<_>>()
            .join("\n")
    );
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../src/services/types.ts");
    if std::env::args().any(|arg| arg == "--check") {
        assert_eq!(
            std::fs::read_to_string(path).unwrap(),
            output,
            "Generated types are stale"
        );
    } else {
        std::fs::write(path, output).unwrap();
    }
}
