// Generated by cargo run -p skilldock-core --example export_types. Do not edit.
export type Policy = { mode: 'off' | 'notify' | 'auto', intervalHours: number, };
export type Skill = { id: string, name: string, description: string, sourceId: string, bundleDigest: string, relativePath: string, version: string, installedAt: string, };
export type Source = { id: string, name: string, kind: string, path: string, url: string, scanSubdir: string, reference: string, version: string, policy: Policy, lastChecked: string, nextCheck: string, status: string, error: string, };
export type Target = { id: string, name: string, tool: string, scope: string, path: string, };
export type Binding = { id: string, skillId: string, targetId: string, path: string, version: string, digest: string, relativePath: string, claims: Array<string>, follow: boolean, };
export type Preset = { id: string, name: string, description: string, skillIds: Array<string>, revision: number, locks: { [key in string]?: Skill }, };
export type Task = { id: string, kind: string, title: string, status: string, message: string, createdAt: string, };
export type Settings = { catalogSites: Array<string>, closeToTray: boolean, theme: string, updateMode: string, updateEndpoint: string, updatePublicKey: string, };
export type Snapshot = { initialized: boolean, storageRoot: string, revision: number, skills: Array<Skill>, sources: Array<Source>, targets: Array<Target>, bindings: Array<Binding>, presets: Array<Preset>, tasks: Array<Task>, settings: Settings, schemaVersion: number, };
export type ScanItem = { path: string, name: string, description: string, status: string, error: string, };
export type ScanResult = { root: string, items: Array<ScanItem>, warnings: Array<string>, };
export type CatalogItem = { slug: string, name: string, description: string, version: string, site: string, };
export type CatalogResult = { items: Array<CatalogItem>, errors: Array<string>, };
export type PlanItem = { skillId: string, targetId: string, path: string, action: string, error: string, };
export type DistributionPlan = { items: Array<PlanItem>, revision: number, };
export type Request = { action: string; [key: string]: unknown }
